version: '3'
services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html:cached
    nginx:
        image: nginx:alpine3.17
        ports:
            - '8080:8080'
        environment:
            TZ: Asia/Tokyo
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            TZ: Asia/Tokyo
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - mysql:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/sql:/docker-entrypoint-initdb.d
    meilisearch:
        image: getmeili/meilisearch:v1.1
        ports:
            - '7700:7700'
        volumes:
            - meilisearch:/meili_data
        environment:
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - '1025:1025'
            - '8025:8025'
    swagger-ui:
        image: swaggerapi/swagger-ui:latest
        ports:
            - '8008:8008'
        environment:
            API_URL: openapi.json
        volumes:
            - ./swagger/openapi.json:/usr/share/nginx/html/openapi.json
    swagger-merger:
        build:
            context: .
            dockerfile: ./docker/swagger-merger/Dockerfile
        command: >
            watch 'swagger-merger -i /swagger/src/index.json -o /swagger/openapi.json' /swagger/src/
        volumes:
            - ./swagger:/swagger
volumes:
    mysql:
    meilisearch:
