on:
  push:
    branches:
      - develop

name: Build and Deploy to Cloud Run
env:
  SERVICE: larastep
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: stg

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Set up project environment variables
        run: |
          touch .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "GCP_REGION=${{ secrets.GCP_REGION }}" >> .env
          echo "GCP_REPOSITORY=${{ secrets.GCP_REPOSITORY }}" >> .env
          echo "GCP_SERVICE_ACCOUNT=${{ secrets.GCP_SERVICE_ACCOUNT }}" >> .env
          echo "GCP_SQL_INSTANCE_PASSWORD=${{ secrets.GCP_SQL_INSTANCE_PASSWORD }}" >> .env
          echo "GCP_SQL_REGION=${{ secrets.GCP_SQL_REGION }}" >> .env
          echo "GCP_VPC_SUBNET_RANGE=${{ secrets.GCP_VPC_SUBNET_RANGE }}" >> .env

      - name: Deploy to Cloud Run
        run: |
          zsh ./scripts/set_project.sh
          zsh ./scripts/deploy_app.sh
          zsh ./scripts/deploy_meilisearch.sh
