on:
  push:
    branches:
      - feature/setting-app

name: Build and Deploy to Cloud Run
env:
  SERVICE: larastep
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: prod

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh

      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

#      - name: Set up project environment variables
#        run: |
#          touch .env
#            cp .env.testing.example .env.testing
#            cp docker/.env.example docker/.env

      - name: Deploy to Cloud Run
        run: |
          zsh ./scripts/set_project.sh
          zsh ./scripts/deploy_app.sh
          zsh ./scripts/deploy_meilisearch.sh
