on:
  push:
    branches:
      - feature/setting-app

name: Build and Deploy to Cloud Run
env:
  SERVICE: larastep
  REGION: asia-northeast1

defaults:
  run:
    shell: zsh

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: prod

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: github-actions@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Deploy to Cloud Run
        run: |
          ls
          echo $SHELL
          make deploy-app
          make deploy-meilisearch
